name: gitleaks

on:
  push:
    branches: [main]  # Change 'main' to your desired branch
  pull_request:
    branches: [main]  # Ensures it also runs for PRs targeting this branch
  workflow_dispatch:

jobs:
  scan:
    name: Gitleaks Scan with Org Key
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks Scan with Org Key
        env:
          GITLEAKS_ORG_KEY: ${{ secrets.GITLEAKSORGKEY }}
        run: |
          gitleaks detect \
            --source=. \
            --config=.gitleaks.toml \
            --report-format=json \
            --report-path=gitleaks-report.json \
            --org-key="$GITLEAKS_ORG_KEY" \
            || true  # Prevent job failure; handled manually below

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
