name: gitleaks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  scan:
    name: Gitleaks Scan with License
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          GITLEAKS_LATEST=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep "browser_download_url" | grep "linux-amd64" | cut -d '"' -f 4)
          curl -Lo gitleaks "$GITLEAKS_LATEST"
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks Scan using License Key
        env:
          GITLEAKS_LICENSE: FA5CF5-97CBD8-784F10-9EB227-B82C8B-V3
        run: |
          gitleaks detect \
            --source=. \
            --config=.gitleaks.toml \
            --report-format=json \
            --report-path=gitleaks-report.json \
            || true  # Let the pipeline continue, can be removed to fail on findings

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json


