name: gitleaks

on:
  push:
    branches:
      - main  # Change if your target branch is different
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (don't fail if secrets are found)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: FA5CF5-97CBD8-784F10-9EB227-B82C8B-V3
        continue-on-error: true
