name: gitleaks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    name: Gitleaks Scan with Org Key
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Gitleaks
        run: |
          GITLEAKS_LATEST=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r '.tag_name')
          curl -sL https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_LATEST}/gitleaks_${GITLEAKS_LATEST#v}_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks Scan with Org Key
        env:
          GITLEAKS_ORG_KEY: FA5CF5-97CBD8-784F10-9EB227-B82C8B-V3
        run: |
          gitleaks detect \
            --source=. \
            --config=.gitleaks.toml \
            --report-format=json \
            --report-path=gitleaks-report.json \
            --org-key="$GITLEAKS_ORG_KEY" \
            || true

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
