name: gitleaks

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch
  pull_request:
    branches:
      - main  # This ensures PRs targeting 'main' will trigger the scan

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: FA5CF5-97CBD8-784F10-9EB227-B82C8B-V3 # Only required for Organizations


