# Only required for Organizations
name: gitleaks

on:
  push:
    branches:
      - main  # Replace with your target branch
  pull_request:
    branches:
      - main  # Replace with your target branch
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks (do not fail on detection)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: FA5CF5-97CBD8-784F10-9EB227-B82C8B-V3
          continue-on-error: true  # Do not fail the job if secrets are found
